### PR TITLE
fix for monster names & ranked monster filter

### PR DESCRIPTION
**Pull request by cybaersam**
sorry it took me sometime to do this request... (lots of stuff going on in rl)
i've reworked the code as the old one didn't work on all the languages
the new code was tested on the english and german version (i don't have the name for the other languages so i set them to english by default)

### CODE REVIEW

**Comment by Icehunter** [comment]
Hi!

I just combined this pull request into some changes I made a copy of your branch. Can you test to ensure it works as well?

I set it up to use regex for case insensitivity.

https://github.com/Icehunter/ffxivapp-plugin-radar/tree/cybaersam-master

You should be able to clone that and copy the files in distribution.

**Comment by cybaersam** [comment]
i will test it as soon as i get home...
and one more thing...
i finally found a list for the monster names in french and japanese
i'll be adding them too

**Comment by Icehunter** [comment]
Thank you :)

**Comment by cybaersam** [comment]
again it took me a bit longer...  and i'm sorry about that...
i've tested the new version and looks like its working just fine...
the only problem i faced was that the app was lagging heavily when i tracked all monsters... (i deactivated the show ranked mobs only option)

as for the names... do i do another pull request ?

**Comment by Icehunter** [comment]
It's possible my merge screwed up something with regards to names.

I'm going to add some checks for the slow down you mentioned. I'll push that in about 10 minutes.

**Comment by cybaersam** [comment]
ok the optimized monster lookup part works great so far.. 
as for the "Meltwater Goobbue" that is shown as a Rank A monster... 
i checked the names multiple times and it's stll showing that one as Rank A....
but so far... that one is the only one i encountered and its a levequest mob
so its not spawned until someone starts that levequest

**Pull request merged**
